apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres  
    spec:
      containers:
      - name: postgres
        image: postgres:10.13
        env:
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres
              key: POSTGRES_PASSWORD
        ports:
          - containerPort: 5432
            protocol: TCP
        envFrom:
          - configMapRef:
              name: postgres-configmap
        volumeMounts:
        - name: postgres-database-storage
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-database-storage
        persistentVolumeClaim:
          claimName: postgres
