---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: webdav
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: "webdav"
  storageClassName: ""
